### ISSUE TITLE
Reverse

### ISSUE THREAD

**Issue by nitrag** [peroper/mapnik-xml-to-mapbox-gl-json#2]
Is the reverse possible? Converting from MapBox GL to Mapnik?

**Comment by oskarer** [comment]
Yes, theoretically it should be possible, but not with the current solution I'm afraid. I'm sure you can reuse parts of the code to do it but it would require quite a rework.

**Comment by pergustas** [comment]
It would be possible with a subset of what MapBoxGL is capable of. Since the the two languages are only partially overlapping you would end up using the full capability of none of them. The value of such an approach will of course depend on your use case.

**Comment by nitrag** [comment]
Understood, thanks!
